[2024-08-15 02:21:40] [INFO    ] discord.client: logging in using static token
[2024-08-15 02:21:44] [INFO    ] discord.gateway: Shard ID 0 has connected to Gateway (Session ID: f691d262dfe70ba84da67857e09ece9b).
[2024-08-15 02:21:47] [ERROR   ] discord.ext.tasks: Unhandled exception in internal background task 'verify_task'.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/root/AkariBot/tools/misc/tasks.py", line 51, in verify_task
    results = await bot.db.fetch("SELECT * FROM verify_codes_discord")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/pool.py", line 570, in fetch
    return await con.fetch(
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 691, in fetch
    return await self._execute(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1794, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1892, in __execute
    result, stmt = await self._do_execute(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1925, in _do_execute
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 433, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 166, in prepare
asyncpg.exceptions.UndefinedTableError: relation "verify_codes_discord" does not exist
