[2024-08-15 01:55:22] [INFO    ] discord.client: logging in using static token
[2024-08-15 01:55:26] [INFO    ] discord.gateway: Shard ID 0 has connected to Gateway (Session ID: 88ca58e908031c87380ba36f0b97408d).
[2024-08-15 01:55:29] [ERROR   ] discord.ext.tasks: Unhandled exception in internal background task 'verify_task'.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/root/AkariBot/tools/misc/tasks.py", line 51, in verify_task
    results = await bot.db.fetch("SELECT * FROM verify_codes_discord")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/pool.py", line 570, in fetch
    return await con.fetch(
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 691, in fetch
    return await self._execute(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1794, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1892, in __execute
    result, stmt = await self._do_execute(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1925, in _do_execute
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 433, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 166, in prepare
asyncpg.exceptions.UndefinedTableError: relation "verify_codes_discord" does not exist
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/auth.py", line 48, in on_guild_join
    await self.guild_change("joined", guild)
  File "/root/AkariBot/cogs/auth.py", line 18, in guild_change
    await self.bot.get_channel(self.channel_id).send(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_guild_role_delete
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/antinuke.py", line 283, in on_role_deletion
    if self.bot.an.get_bot_perms(role.guild):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/AkariBot/tools/helpers.py", line 107, in get_bot_perms
    guild.me.guild_permissions.ban_members,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'guild_permissions'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/antinuke.py", line 361, in on_member_role_give
    r for r in after.roles if not r in before.roles and r.is_assignable()
                                                        ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/discord/role.py", line 324, in is_assignable
    return not self.is_default() and not self.managed and (me.top_role > self or me.id == self.guild.owner_id)
                                                           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'top_role'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/events/messages.py", line 380, in imageonly_check
    if not message.guild.me.guild_permissions.manage_messages:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'guild_permissions'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_member_remove
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/antinuke.py", line 415, in on_kick_action
    if self.bot.an.get_bot_perms(member.guild):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/AkariBot/tools/helpers.py", line 107, in get_bot_perms
    guild.me.guild_permissions.ban_members,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'guild_permissions'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_guild_remove
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/auth.py", line 41, in on_guild_remove
    await self.guild_change("left", guild)
  File "/root/AkariBot/cogs/auth.py", line 18, in guild_change
    await self.bot.get_channel(self.channel_id).send(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
[2024-08-15 01:56:06] [ERROR   ] discord.client: Ignoring exception in on_member_remove
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/logging.py", line 197, in on_member_remove
    if record := await self.bot.db.fetchval("SELECT members FROM logging WHERE guild_id = $1", member.guild.id):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/pool.py", line 588, in fetchval
    return await con.fetchval(
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 715, in fetchval
    data = await self._execute(query, args, 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1794, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1892, in __execute
    result, stmt = await self._do_execute(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 1925, in _do_execute
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/asyncpg/connection.py", line 433, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 166, in prepare
asyncpg.exceptions.UndefinedColumnError: column "members" does not exist
[2024-08-15 01:56:26] [ERROR   ] discord.client: Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/auth.py", line 48, in on_guild_join
    await self.guild_change("joined", guild)
  File "/root/AkariBot/cogs/auth.py", line 18, in guild_change
    await self.bot.get_channel(self.channel_id).send(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
[2024-08-15 01:56:37] [ERROR   ] discord.client: Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/auth.py", line 48, in on_guild_join
    await self.guild_change("joined", guild)
  File "/root/AkariBot/cogs/auth.py", line 18, in guild_change
    await self.bot.get_channel(self.channel_id).send(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
[2024-08-15 01:56:52] [ERROR   ] discord.client: Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/discord/client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "/root/AkariBot/cogs/auth.py", line 48, in on_guild_join
    await self.guild_change("joined", guild)
  File "/root/AkariBot/cogs/auth.py", line 18, in guild_change
    await self.bot.get_channel(self.channel_id).send(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
